image:
  file: .gitpod.Dockerfile

tasks:
  - init: npm install
    command: npm run dev
  - init: cd client && npm install
    command: cd client && npm start

ports:
  - port: 3000
    onOpen: open-preview
  - port: 4000
    onOpen: open-preview
